export default function Terms() {
  return (
    <div className="max-w-4xl mx-auto p-8 text-gray-800">
      <h1 className="text-4xl font-bold mb-6">Terms of Service</h1>

      <p className="mb-4">
        Welcome to TikTonik! By using our website and services, you agree to the
        following terms. Please read them carefully.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">
        1. Acceptance of Terms
      </h2>
      <p className="mb-4">
        By accessing or using TikTonik, you confirm that you have read,
        understood, and agree to be bound by these Terms of Service.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">
        2. Description of Service
      </h2>
      <ul className="list-disc pl-6 mb-4">
        <li>Automated video creation using AI based on social trends.</li>
        <li>Real-time trend analysis and content optimization.</li>
        <li>
          Scheduling and uploading videos to TikTok, Instagram, YouTube Shorts,
          and Facebook.
        </li>
        <li>Multi-account support and user customization features.</li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-2">
        3. User Responsibilities
      </h2>
      <ul className="list-disc pl-6 mb-4">
        <li>
          You must provide accurate information and keep your account secure.
        </li>
        <li>You are responsible for all content uploaded via your account.</li>
        <li>
          You agree not to upload prohibited content (hate, violence, or sexual
          material).
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-2">
        4. Payment and Subscription
      </h2>
      <ul className="list-disc pl-6 mb-4">
        <li>Monthly: $9.99/month</li>
        <li>3-Month Plan: $25.00</li>
        <li>Annual: $99.00</li>
        <li>
          You can cancel anytime. Annual subscriptions are eligible for prorated
          refunds.
        </li>
      </ul>

      <h2 className="text-2xl font-semibold mt-6 mb-2">
        5. Intellectual Property
      </h2>
      <p className="mb-4">
        All content generated by TikTonik's AI is owned by the user, but
        TikTonik retains the right to use anonymized performance data for
        service improvement.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">6. Termination</h2>
      <p className="mb-4">
        We reserve the right to suspend or terminate accounts that violate these
        Terms or abuse our services.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">
        7. Limitation of Liability
      </h2>
      <p className="mb-4">
        TikTonik is provided "as is." We are not liable for indirect damages
        resulting from your use of the service.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">8. Changes to Terms</h2>
      <p className="mb-4">
        We may update these Terms occasionally. Continued use of TikTonik means
        you accept the changes.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-2">9. Contact</h2>
      <p className="mb-4">
        For any questions or concerns regarding these Terms, please contact us
        at support@tiktonik.ai.
      </p>
    </div>
  );
}
